ratings:
  namespace: student18-bookinfo-dev
  image: ghcr.io/jednuth156/bookinfo-ratings
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  host: bookinfo.dev.opsta.net
  path: "/student18/ratings(/|$)(.*)"
  serviceType: ClusterIP  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-dev-ratings-mongodb:27017/ratings